services:
  mqtt_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  weather_requester:
    depends_on:
      - mqtt_broker
    entrypoint: ["sh", "-c", "sleep 5 && python weather_requester.py"]
    build:
      context: ./weather_requester
    volumes:
      - ./weather_requester:/app
    environment:
      - MQTT_BROKER=mqtt_broker
    env_file:
      - .env
    networks:
      - default

  weather_subscriber:
    build:
      context: ./weather_subscriber
    volumes:
      - ./weather_subscriber:/app
    environment:
      - MQTT_BROKER=mqtt_broker
    env_file:
      - .env
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge
