# Użycie obrazu Python
FROM python:3.10-slim

# Ustawienie katalogu roboczego
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "weather_requester.py"]