# Base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy the Python script to the container
COPY weather_requester.py .

# Install dependencies
RUN pip install requests

# Set environment variable (can be overridden in docker-compose.yml)
ENV LOCATION=Warsaw

# Run the script
CMD ["python", "weather_requester.py"]