version: "3"
services:
  weather_requester:
    build: .
    env_file:
      - .env  # Wczytuje zmienne środowiskowe z pliku .env
    container_name: weather_requester-1
    command: python weather_requester.py
    restart: always