# Użycie obrazu Python
FROM python:3.10-slim

# Ustawienie katalogu roboczego
WORKDIR /app

# Kopiowanie plików do obrazu
COPY weather_requester.py /app/
COPY requirements.txt /app/

# Instalacja zależności
RUN pip install -r requirements.txt

# Ustawienie zmiennej środowiskowej domyślnie
ENV location="10776"

# Uruchamianie skryptu
CMD ["python", "weather_requester.py"]
