FROM python:3.9-slim

WORKDIR /app

COPY weather_requester.py /app/
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD ["python", "weather_requester.py"]
